---
title: "P8105 Final Project: Trends in COVID cases, deaths, and vaccinations in the United States and New York City"
author: Heidi Lumish (hl2738), Louis Sharp (lzs2109), Philip Kim (pk2711), Kayla Boyer (kb3066), Yujia Li (yl4923)
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Motivation
In light of the recent and ongoing COVID-19 pandemic, we are interested in understanding how COVID-19 vaccination has impacted the trajectory of the pandemic in the United States and in New York City Specifically. We are interested in comparing trends in COVID-19 cases and deaths pre- and post-vaccination in the United States. We would also like to understand patterns of vaccine hesitancy and how this has impacted vaccine uptake and COVID cases and mortality across the country. We will focus in specifically on New York City and similarly describe trends in COVID-19 disease and vaccinations.

## Anticipated data sources
- [NY Times COVID-19 data set](https://github.com/nytimes/covid-19-data/)
- [Our World COVID-19 data](https://github.com/owid/covid-19-data/tree/master/public/data/vaccinations)
- [CDC's United States COVID-19 Cases and Deaths by State Over Time](https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36)
- CDC's COVID-19 deaths by: [Sex and age](https://data.cdc.gov/NCHS/Provisional-COVID-19-Deaths-by-Sex-and-Age/9bhg-hcku), [Race and Hispanic origin](https://data.cdc.gov/NCHS/Provisional-COVID-19-Deaths-Distribution-of-Deaths/pj7m-y5uh), [Week and Urbanicity](https://data.cdc.gov/NCHS/Provisional-COVID-19-Deaths-by-Week-and-Urbanicity/hkhc-f7hg), [Educational Attainment](https://data.cdc.gov/NCHS/AH-Provisional-COVID-19-Deaths-by-Race-and-Educati/i6ej-9eac)
- [CDC's Vaccine hesitancy for COVID-19: county and local estimates](https://data.cdc.gov/Vaccinations/Vaccine-Hesitancy-for-COVID-19-County-and-local-es/q9mh-h2tw)
- CDC's COVID-19 Vaccine Distribution Allocations by Jurisdiction - [Pfizer](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/saz5-9hgg), [Moderna](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/b7pe-5nws), [J&J](https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/w9zu-fywh)
- [CDC's COVID-19 vaccinations in the United States, County](https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh)

## Intended final products
- Line graphs showing trends in cases and deaths in the U.S. and NYC, respectively
- Similar graphs with markers for initiation of vaccine distribution
- Bar graphs showing differences in COVID-19 deaths by different subgroups (age, sex, race, etc.)
- Line graph showing trends in mask usage, disease rates, and vaccine rates
- Maps demonstrating allocation of each vaccine type
- Maps showing trends in vaccine hesitancy
- Maps showing trends in vaccination
- Scatterplots with linear regression lines showing case rates and death rates before and after vaccination
- Seasonal rates of COVID-19 infection, will subset data by quarters

Maps can be combined using plotly
Make some of the figures/maps interactive

## Planned analyses
We are interested in exploring the theoretical effect that the vaccine can have on reducing the spread of the virus and how this compares with the trajectory of cases we are experiencing in the U.S.
- linear models for case rates before and after vaccine roll-out
- predictive factors for vaccination/vaccine hesitancy

## Planned timeline
- 11/14-11/20: Project review meeting, exploratory data analysis, website layout
- 11/21-11/27: Data visualization with graphs, charts, tables
- 11/28-12/3: Results analysis, discussion, and conclusions
- 12/3-12/6: Editing, final touches
- 12/6: Report complete
- 12/7: Work on webcast
- 12/11: Final project submission
